all: membench-0.png storage-0.png matmul-0.png engineering-0.png

membench-0.png: membench.tex
	pdflatex -shell-escape membench.tex

storage-0.png: storage.tex
	pdflatex -shell-escape storage.tex

matmul-0.png: matmul.tex
	pdflatex -shell-escape matmul.tex

engineering-0.png: engineering.tex
	pdflatex -shell-escape engineering.tex
